#!/usr/bin/env bash
set -euo pipefail

# v2: ingress-nginx is removed.
# This script now only applies tenant namespaces/policies generated by the tenant manifest generator.
# API Gateway (Gateway API / Envoy Gateway) is installed in a later step.

TENANT_MANIFEST="${TENANT_MANIFEST:-deploy/k8s/networking/tenants/generated/tenants.generated.yaml}"

echo "[networking] Applying tenant namespaces/policies from: ${TENANT_MANIFEST}"
kubectl apply -f "${TENANT_MANIFEST}" >/dev/null


echo ""
echo "[networking] Done."
echo "Access (kind demo):"
echo "  - control-plane-api NodePort: http://localhost:30080"
echo "  - tenant-aware routing: send Host header (example):"
echo "      curl -H 'Host: tenant-a.mlops.local' http://localhost:30080/api/v1/overview"
