apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: run-orchestrator
  namespace: mlops-system
spec:
  scaleTargetRef:
    name: run-orchestrator
  pollingInterval: 5
  cooldownPeriod: 30
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: "nats.nats.svc.cluster.local:8222"
        account: "$G"
        stream: "MLOPS_RUNS"
        consumer: "run-orchestrator"
        lagThreshold: "50"
        activationLagThreshold: "5"
        useHttps: "false"
